[package]
name = "miru"
version = "0.0.1-alpha"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-mal={path="../lib-mal"}
tokio = {version = "1.8.2", features = ["full"]}
webbrowser = "0.5.5"
directories = "3.0"
