name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create Secret File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "miru/src/secret"
        FILE_DATA: ${{ secrets.MALID }}

    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
