name: get secrets
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: print secrets
      run: |
          echo $DEV_ENV_FILE >> src/secret
          cat src/secret
      shell: bash
      env:
        DEV_ENV_FILE : ${{secrets.MALID}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       name: DEV_SECRET_FILE
       path: src/secret
